export const name = [
  "M",
  "o",
  "h",
  "a",
  "m",
  "m",
  "e",
  "d",
  "n",
  "u",
  "r",
  " ",
  "S",
  "e",
  "i",
  "d",
];

export const socials = [
  {
    name: "X",
    color: "#181717",
    link: "https://x.com/monur2025",
  },
  {
    name: "Github",
    color: "#181717",
    link: "https://github.com/mamebb2023",
  },
  {
    name: "LinkedIn",
    color: "#0077b5",
    link: "https://linkedin.com/in/mohammednur-seid/",
  },
  {
    name: "Upwork",
    color: "#6FDA44",
    link: "https://www.upwork.com/freelancers/~01e488d551441650a7?mp_source=share",
  },
];

export const links = [
  // {
  //   name: "Home",
  //   href: "#home",
  // },
  {
    name: "About",
    href: "#about",
  },
  {
    name: "Projects",
    href: "#projects",
  },
  // {
  //   name: "Services",
  //   href: "#blog",
  // },
  {
    name: "Contact",
    href: "#contact",
  },
];

export const projects = [
  {
    color: "#dc00c9",
    title: "LotusFlow",
    mini_title: "AI-Powered React Component Generator",
    description: "AI-powered tool to generate React components just from text prompts.",
    role: "Full Stack Developer",
    links: { live: "https://lotusflow.vercel.app/" },
    duration: "Aug 2025 - Present",
    features: [
      "AI-Powered Component Generation",
      "Real-time Design Preview",
      "Real-time Code Preview",
      "Customizable Props",
      "Export Options",
      "Responsive Design",
    ],
    logo: "/assets/lotusflow/lotusflow-logo.png",
    images: [
      "/assets/lotusflow/lotusflow-1.png",
      "/assets/lotusflow/lotusflow-2.png",
      "/assets/lotusflow/lotusflow-3.png",
      "/assets/lotusflow/lotusflow-4.png",
      "/assets/lotusflow/lotusflow-5.png",
      "/assets/lotusflow/lotusflow-6.png",
    ],
    bestProject: true,
  },
  {
    color: "#6BCF91",
    title: "WeMD Africa",
    mini_title: "Online Dermatology Clinic",
    description: "Connecting patients with dermatologists across Africa.",
    role: "Front-end Developer",
    links: { live: "https://wemd-africa.vercel.app/" },
    duration: "Nov 2024 - Dec 2024",
    features: [
      "Light/Dark Theme",
      "Fully Responsive",
      "Localization (English and Amharic)",
      "Doctor Consultation Stepped Form",
      "Chat Page",
      "Animations ...",
    ],
    logo: "/assets/wemd/wemd-logo.webp",
    images: [
      "/assets/wemd/wemd-1.jpg",
      "/assets/wemd/wemd-2.jpg",
      "/assets/wemd/wemd-3.jpg",
      "/assets/wemd/wemd-4.jpg",
      "/assets/wemd/wemd-5.jpg",
      "/assets/wemd/wemd-6.jpg",
    ],
    bestProject: true,
    forClient: true,
  },
  {
    color: "#00D9FF",
    forClient: true,
    title: "SanAI",
    mini_title: "Your Personal AI Doctor",
    description: "AI-powered health assistant for personalized care.",
    role: "Full Stack Developer",
    links: { live: "https://sanai-nu.vercel.app/" },
    duration: "May 2025 - Jul 2025",
    features: [
      "AI Voice Chatbot",
      "Image Recognition",
      "Symptom Checker",
      "Health Tips",
      "Personalized Health Insights",
      "Responsive Design",
    ],
    logo: "/assets/sanai/sanai-logo.png",
    images: [
      "/assets/sanai/sanai-1.png",
      "/assets/sanai/sanai-2.png",
      "/assets/sanai/sanai-3.png",
      "/assets/sanai/sanai-4.png",
      "/assets/sanai/sanai-5.png",
      "/assets/sanai/sanai-6.png",
    ],
  },
  {
    color: "#8c00ff",
    title: "Brainwave",
    mini_title: "Modern & Responsive SaaS Landing Page",
    description:
      "A sleek and modern React website showcasing the latest in web design.",
    role: "Front-end Developer",
    links: {
      live: "https://brainwave-iota-five-26.vercel.app/",
      code: "https://github.com/mamebb2023/brainwave/",
    },
    duration: "Feb 2024 - Mar 2024",
    features: [
      "Responsive Design",
      "Modern UI Components",
      "Smooth Animations",
      "SEO Optimized",
      "Cross-Browser Compatibility",
    ],
    logo: "/assets/brainwave/brainwave-logo.png",
    images: [
      "/assets/brainwave/brainwave-1.png",
      "/assets/brainwave/brainwave-2.png",
      "/assets/brainwave/brainwave-3.png",
      "/assets/brainwave/brainwave-4.png",
      "/assets/brainwave/brainwave-5.png",
      "/assets/brainwave/brainwave-6.png",
    ],
  },
  {
    color: "#1010a0",
    title: "CalHabit",
    mini_title: "Habit tracking web app",
    description:
      "Modern habit tracker designed to help you stay on top of your goals",

    role: "Full Stack Developer",
    links: { live: "https://cal-habit.vercel.app/", code: "https://github.com/mamebb2023/CalHabit" },
    features: ["Easy Habit Tracking", "Responsive Design"],
    logo: "/assets/calhabit/calhabit-logo.png",
    images: [
      "/assets/calhabit/calhabit-1.png",
      "/assets/calhabit/calhabit-2.png",
      "/assets/calhabit/calhabit-3.png",
      "/assets/calhabit/calhabit-4.png",
      "/assets/calhabit/calhabit-5.png",
      "/assets/calhabit/calhabit-6.png",
    ],
  },
];

export const miniProjects = [
  {
    color: "#ff8c00",
    title: "DevOverflow | Q&A Web Application",
    description:
      "A modern Q&A platform designed to foster knowledge sharing and collaboration.",
    role: "Full Stack Developer",
    links: [
      "https://github.com/mamebb2023/nextjs",
    ],
    duration: "Sep 2024 - Nov 2024",
    features: [
      "Clerk User Authentication",
      "Question and Answer System",
      "Upvote/Downvote Mechanism",
      "Commenting System",
      "Responsive Design",
      "Admin Dashboard",
    ],
    logo: "/assets/devflow/devflow-logo.png",
    image: "/assets/devflow/devflow-1.png",
  },
  {
    color: "#008c00",
    title: "Ethio-Commerce",
    mini_title: "Secure & User-Friendly E-Commerce",
    description: "E-commerce platform designed to simplify online shopping",
    role: "Front-end Developer",
    links: ["https://github.com/mamebb2023/ethio-commerce/"],
    features: [
      "Secure Login System",
      "Easy Cart Management",
      "Streamlined Admin Tools",
    ],
    logo: "/assets/et/et-logo.png",
    images: ["/assets/et/et-1.png"],
  },
  {
    color: "#056c0f",
    title: "TraderPro",
    description: "Modern landing page made with React website",
    role: "Front-end Developer",
    links: [
      "https://traderpro-1.vercel.app/",
      "https://github.com/mamebb2023/TraderPro",
    ],
    features: ["Responsive Design", "Smooth Scrolling", "Animated Elements"],
    logo: "/assets/tp/tp-logo.webp",
    image: "/assets/tp/tp-1.png",
  },
  {
    color: "#ffff00",
    title: "Maze Game",
    description: "C-powered maze challenge built with the SDL2 Engine. ",
    role: "Software Developer",
    links: [
      "https://mamez7878.github.io/maze/",
      "https://github.com/mamebb2023/Maze-Project",
    ],
    features: ["Interactive Gameplay", "Easy control"],
    logo: "/assets/maze/maze-logo.png",
    image: "/assets/maze/maze-1.png",
  },
];

export const testimonials = [
  {
    name: "Yared Haile",
    role: "CEO, WeMD Africa",
    avatar: "YH",
    color: "#6BCF91",
    text: "Mohammednur delivered a stunning, fully responsive platform that exceeded every expectation. His attention to detail and ability to translate complex requirements into clean, intuitive UI is remarkable. The localization and animation work was top-tier.",
  },
  {
    name: "Liya Tesfaye",
    role: "Product Manager, SanAI",
    avatar: "LT",
    color: "#00D9FF",
    text: "Working with Mohammednur was an absolute pleasure. He built our AI health app from scratch, integrating voice chat and image recognition seamlessly. His full-stack skills and proactive communication made the whole process smooth and efficient.",
  },
  {
    name: "Daniel Worku",
    role: "Startup Founder",
    avatar: "DW",
    color: "#dc00c9",
    text: "I hired Mohammednur for a complex React project and was blown away by the quality of work. He's not just a developer — he thinks like a designer too. LotusFlow is proof of that. Efficient, talented, and reliable.",
  },
  {
    name: "Sara Bekele",
    role: "Frontend Lead, DevCo",
    avatar: "SB",
    color: "#8c00ff",
    text: "Mohammednur is the kind of developer every team wants. He writes clean, maintainable code and has a sharp eye for UX. He jumped into our codebase quickly and delivered high-quality components on a tight deadline.",
  },
  {
    name: "Abebe Girma",
    role: "CTO, FinTech Startup",
    avatar: "AG",
    color: "#ff8c00",
    text: "Outstanding full-stack skills. Mohammednur built and deployed our entire web app with great performance and security in mind. He was always available, communicated clearly, and never missed a deadline.",
  },
];
