import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import { Faculty_Glyphic } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Faculty_Glyphic({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-cabin-variable antialiased bg-gray-50`}>
        <ReactLenis root>{children}</ReactLenis>
      </body>
    </html>
  );
}
